In [4]:
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim

In [71]:
dat = pd.read_csv('Jackson_NIre.csv')
dat

,Site,latitude,longitude,Intertidal slope,MSTR (m),H0 (mean Hs),Hb (from mean),"T (mean, s)",D50 (mm),RTR (Hmean),Ws,Dean parameter
0,Rossnowlagh,54.554352,-8.209775,0.0139,3.3,2.18,2.49,6.88,0.140,1.33,0.0154,23.38
1,Tramore Strand,52.152397,-7.112763,0.0218,3.4,2.18,2.49,6.88,0.180,1.37,0.0175,20.62
2,"Dooey beach, Magheraroarty",55.152830,8.155428,0.0202,3.4,2.18,2.49,6.88,0.210,1.37,0.0189,19.09
3,"Tra Beg beach, Downings",55.192982,-7.836669,0.0134,3.4,2.18,2.49,6.88,0.140,1.37,0.0154,23.38
4,Culdaff,55.286966,-7.166544,0.0446,2.9,2.18,2.49,6.88,0.230,1.16,0.0198,18.24
5,Magilligan,55.149232,-6.911044,0.0375,1.6,2.18,2.49,6.88,0.190,0.64,0.0180,20.07
6,Benone,55.163580,-6.877427,0.0194,1.6,2.05,2.40,6.89,0.157,0.64,0.0164,21.00
7,Castlerock,55.164820,-6.788414,0.0214,1.5,2.26,2.62,7.11,0.166,0.57,0.0168,21.67
8,Portstewart,55.182910,-6.718701,0.0246,1.5,2.26,2.62,7.11,0.157,0.57,0.0164,22.28
9,West Portrush,55.202304,-6.655600,0.0320,1.5,2.34,2.70,7.17,0.186,0.56,0.0178,20.94
10,East Portrush,55.206520,-6.613315,0.0352,1.5,2.34,2.70,7.17,0.197,0.56,0.0183,20.35
11,Runkerry,55.230840,-6.519184,0.0329,1.5,2.18,2.49,6.88,0.280,0.52,0.0218,15.23
12,White Park Bay,55.235180,-6.403564,0.0350,1.2,2.41,2.77,7.22,0.229,0.43,0.0198,19.24
13,Ballycastle,55.200688,-6.250282,0.0823,0.9,2.52,2.89,7.36,0.634,0.31,0.0329,11.85
14,Cushendun,55.125247,-6.042348,0.1037,1.6,1.28,1.38,4.61,0.397,1.16,0.0260,11.53
15,Redbay,55.065955,-6.060966,0.0340,1.4,1.36,1.46,4.71,0.169,0.96,0.0170,18.31
16,Ballygalley,54.898066,-5.857875,0.0639,1.9,1.52,1.62,4.89,0.218,1.17,0.0193,17.23
17,Helens Bay,54.675499,-5.736003,0.0522,3.3,1.37,1.47,4.70,0.248,2.25,0.0206,15.23
18,Millisle,54.607820,-5.528463,0.0183,3.5,1.38,1.48,4.72,0.141,2.37,0.0155,20.26
19,Cloughy Bay,54.436630,5.468761,0.0280,3.6,1.55,1.65,4.90,0.170,2.18,0.0170,19.79
20,Ballyhornan,54.300135,-5.558462,0.0337,3.8,1.38,1.48,4.72,0.286,2.57,0.0221,14.23
21,Tyrella,54.250000,-5.766667,0.0088,5.0,1.38,1.48,4.72,0.137,3.38,0.0153,20.55
22,"Dundrum, Newcastle",54.221498,-5.888508,0.0095,5.0,1.38,1.48,4.72,0.150,3.38,0.0160,19.64
23,Kilkeel,54.062666,-6.005995,0.0511,4.0,1.38,1.48,4.72,0.233,2.70,0.0199,15.76
24,Cranfield Point,54.703803,-6.363024,0.0161,4.0,1.53,1.63,4.88,0.214,2.45,0.0191,17.51

In [ ]:
##geocode beach locations

In [69]:
# # s = dat['Site'][24]+' Northern Ireland'
# s = 'Dooey Beach Northern Ireland'
# print(s)
# locator = Nominatim(user_agent="myGeocoder")
# location = locator.geocode(s)
# print(location.latitude)
# print(location.longitude)

In [32]:
# LATS = []
# LONS = []
# for s in dat['Site']:
#     location = locator.geocode(s)
#     try:
#         LONS.append(location.longitude)
#         LATS.append(location.latitude)
#     except:
#         LONS.append(np.nan)
#         LATS.append(np.nan)

In [33]:
# LONS

In [34]:
# dat['latitude'] = LATS
# dat['longitude'] = LONS
# dat

In [72]:
dat = dat.dropna()
dat

,Site,latitude,longitude,Intertidal slope,MSTR (m),H0 (mean Hs),Hb (from mean),"T (mean, s)",D50 (mm),RTR (Hmean),Ws,Dean parameter
0,Rossnowlagh,54.554352,-8.209775,0.0139,3.3,2.18,2.49,6.88,0.140,1.33,0.0154,23.38
1,Tramore Strand,52.152397,-7.112763,0.0218,3.4,2.18,2.49,6.88,0.180,1.37,0.0175,20.62
2,"Dooey beach, Magheraroarty",55.152830,8.155428,0.0202,3.4,2.18,2.49,6.88,0.210,1.37,0.0189,19.09
3,"Tra Beg beach, Downings",55.192982,-7.836669,0.0134,3.4,2.18,2.49,6.88,0.140,1.37,0.0154,23.38
4,Culdaff,55.286966,-7.166544,0.0446,2.9,2.18,2.49,6.88,0.230,1.16,0.0198,18.24
5,Magilligan,55.149232,-6.911044,0.0375,1.6,2.18,2.49,6.88,0.190,0.64,0.0180,20.07
6,Benone,55.163580,-6.877427,0.0194,1.6,2.05,2.40,6.89,0.157,0.64,0.0164,21.00
7,Castlerock,55.164820,-6.788414,0.0214,1.5,2.26,2.62,7.11,0.166,0.57,0.0168,21.67
8,Portstewart,55.182910,-6.718701,0.0246,1.5,2.26,2.62,7.11,0.157,0.57,0.0164,22.28
9,West Portrush,55.202304,-6.655600,0.0320,1.5,2.34,2.70,7.17,0.186,0.56,0.0178,20.94
10,East Portrush,55.206520,-6.613315,0.0352,1.5,2.34,2.70,7.17,0.197,0.56,0.0183,20.35
11,Runkerry,55.230840,-6.519184,0.0329,1.5,2.18,2.49,6.88,0.280,0.52,0.0218,15.23
12,White Park Bay,55.235180,-6.403564,0.0350,1.2,2.41,2.77,7.22,0.229,0.43,0.0198,19.24
13,Ballycastle,55.200688,-6.250282,0.0823,0.9,2.52,2.89,7.36,0.634,0.31,0.0329,11.85
14,Cushendun,55.125247,-6.042348,0.1037,1.6,1.28,1.38,4.61,0.397,1.16,0.0260,11.53
15,Redbay,55.065955,-6.060966,0.0340,1.4,1.36,1.46,4.71,0.169,0.96,0.0170,18.31
16,Ballygalley,54.898066,-5.857875,0.0639,1.9,1.52,1.62,4.89,0.218,1.17,0.0193,17.23
17,Helens Bay,54.675499,-5.736003,0.0522,3.3,1.37,1.47,4.70,0.248,2.25,0.0206,15.23
18,Millisle,54.607820,-5.528463,0.0183,3.5,1.38,1.48,4.72,0.141,2.37,0.0155,20.26
19,Cloughy Bay,54.436630,5.468761,0.0280,3.6,1.55,1.65,4.90,0.170,2.18,0.0170,19.79
20,Ballyhornan,54.300135,-5.558462,0.0337,3.8,1.38,1.48,4.72,0.286,2.57,0.0221,14.23
21,Tyrella,54.250000,-5.766667,0.0088,5.0,1.38,1.48,4.72,0.137,3.38,0.0153,20.55
22,"Dundrum, Newcastle",54.221498,-5.888508,0.0095,5.0,1.38,1.48,4.72,0.150,3.38,0.0160,19.64
23,Kilkeel,54.062666,-6.005995,0.0511,4.0,1.38,1.48,4.72,0.233,2.70,0.0199,15.76
24,Cranfield Point,54.703803,-6.363024,0.0161,4.0,1.53,1.63,4.88,0.214,2.45,0.0191,17.51

In [73]:
dat.keys()

Index(['Site', 'latitude', 'longitude', 'Intertidal slope', 'MSTR (m)',
       'H0 (mean Hs)', 'Hb (from mean)', 'T (mean, s)', 'D50 (mm)',
       'RTR (Hmean)', 'Ws', 'Dean parameter'],
      dtype='object')

In [74]:
dat = dat[['latitude', 'longitude', 'Intertidal slope', 'MSTR (m)',
       'H0 (mean Hs)', 'T (mean, s)', 'D50 (mm)']].copy()

In [75]:
dat.to_csv('NI_GrainSize_waves_slopes_tide_merged.csv')